import { useCallback, useState, type FormEvent } from 'react'
import type { CloudCompany, CurrencyCode, PageOrientation, PaperSize } from '../../types'
import { SupabaseCompanyRepository } from '../../services/repositories/supabaseRepository'
import { useRepositoryList } from '../../hooks/useRepositoryList'
import { useAuth } from '../../features/auth/AuthProvider'
import { can } from '../../features/auth/entitlements'
const repository=new SupabaseCompanyRepository()
const empty=():CloudCompany=>({id:crypto.randomUUID(),name:'',address:'',telephone:'',email:'',registrationNumber:'',logo:'',authorizedName:'',authorizedDesignation:'',themeColor:'#0b1f3a',referencePrefix:'PS',defaultCurrency:'LKR',defaultPaperSize:'a4',defaultOrientation:'portrait',showSliplyBranding:true,isDefault:false,archivedAt:null})
export function CompaniesPage(){const auth=useAuth();const load=useCallback(()=>repository.list(),[]);const {data,loading,error,reload}=useRepositoryList(load);const [draft,setDraft]=useState(empty);const [message,setMessage]=useState('');const set=(key:keyof CloudCompany,value:unknown)=>setDraft({...draft,[key]:value});const submit=async(e:FormEvent)=>{e.preventDefault();setMessage('');try{await repository.save(draft);setDraft(empty());await reload();setMessage('Company saved.')}catch(x){setMessage(x instanceof Error?x.message:'Could not save company.')}};return <main className="cloud-page"><h1>Companies</h1><p>Company edits do not rewrite historical payment snapshots.</p><form className="management-form" onSubmit={submit}><label>Name<input required value={draft.name} onChange={e=>set('name',e.target.value)}/></label><label>Address<textarea required value={draft.address} onChange={e=>set('address',e.target.value)}/></label><label>Reference prefix<input required pattern="[A-Z0-9]+(-[A-Z0-9]+)*" value={draft.referencePrefix} onChange={e=>set('referencePrefix',e.target.value.toUpperCase())}/></label><label>Default currency<select value={draft.defaultCurrency} onChange={e=>set('defaultCurrency',e.target.value as CurrencyCode)}>{['LKR','USD','EUR','GBP','INR','AUD','CAD','SGD'].map(x=><option key={x}>{x}</option>)}</select></label><label>Paper size<select value={draft.defaultPaperSize} onChange={e=>set('defaultPaperSize',e.target.value as PaperSize)}>{['a4','a5','b5','letter'].map(x=><option key={x}>{x.toUpperCase()}</option>)}</select></label><label>Orientation<select value={draft.defaultOrientation} onChange={e=>set('defaultOrientation',e.target.value as PageOrientation)}><option>portrait</option><option>landscape</option></select></label><label><input type="checkbox" checked={draft.isDefault} onChange={e=>set('isDefault',e.target.checked)}/> Default company</label><label><input type="checkbox" checked={draft.showSliplyBranding} disabled={!can(auth.plan,'removeSliplyBranding')} onChange={e=>set('showSliplyBranding',e.target.checked)}/> Show “Generated with Sliply”</label><button className="button primary">{data.some(x=>x.id===draft.id)?'Update':'Add'} company</button></form>{message&&<p role="status">{message}</p>}{loading?<p role="status">Loading companies…</p>:error?<p role="alert">{error}</p>:<ul className="cloud-list">{data.map(company=><li key={company.id}><button className="record-button" onClick={()=>setDraft(company)}><strong>{company.name}</strong><span>{company.isDefault?'Default':''}</span></button><button className="button danger-subtle" onClick={()=>confirm(`Archive ${company.name}? Historical payments will remain unchanged.`)&&void repository.archive(company.id).then(reload)}>Archive</button></li>)}</ul>}</main>}
