import type { User } from '@supabase/supabase-js'
import type { CloudCompany, CloudPaymentRecord, CloudRecipient, PaymentSlip, PaymentSlipFilters } from '../../types'
import { requireSupabase } from '../supabase/client'
import type { CompanyRepository, PaymentSlipRepository, RecipientRepository } from './contracts'
import { companyToRow, recipientToRow, slipToRow } from './mappers'

const currentUser = async (): Promise<User> => { const { data, error } = await requireSupabase().auth.getUser(); if (error || !data.user) throw error || new Error('Your session expired. Sign in again.'); return data.user }
const fail = (error: { message: string } | null) => { if (error) throw new Error(error.message) }
const companyFromRow = (row: Record<string, any>): CloudCompany => ({ id: row.id, name: row.name, address: row.address, telephone: row.telephone || '', email: row.email || '', registrationNumber: row.registration_number || '', logo: row.logo_path || '', authorizedName: row.authorized_name || '', authorizedDesignation: row.authorized_designation || '', themeColor: row.theme_color, referencePrefix: row.reference_prefix, defaultCurrency: row.default_currency, defaultPaperSize: row.default_paper_size, defaultOrientation: row.default_orientation, showSliplyBranding: row.show_sliply_branding, isDefault: row.is_default, archivedAt: row.archived_at })
const recipientFromRow = (row: Record<string, any>): CloudRecipient => ({ id: row.id, name: row.name, identification: row.identification || '', role: row.role || '', address: row.address || '', email: row.email || '', telephone: row.telephone || '', archivedAt: row.archived_at })

export class SupabaseCompanyRepository implements CompanyRepository {
  async list() { const { data, error } = await requireSupabase().from('companies').select('*').is('archived_at', null).order('name'); fail(error); return (data || []).map(companyFromRow) }
  async save(company: CloudCompany) { const user = await currentUser(); const { data, error } = await requireSupabase().from('companies').upsert(companyToRow(company, user.id)).select().single(); fail(error); return companyFromRow(data) }
  async archive(id: string) { const { error } = await requireSupabase().from('companies').update({ archived_at: new Date().toISOString() }).eq('id', id); fail(error) }
}
export class SupabaseRecipientRepository implements RecipientRepository {
  async list() { const { data, error } = await requireSupabase().from('recipients').select('*').is('archived_at', null).order('name'); fail(error); return (data || []).map(recipientFromRow) }
  async save(recipient: CloudRecipient) { const user = await currentUser(); const { data, error } = await requireSupabase().from('recipients').upsert(recipientToRow(recipient, user.id)).select().single(); fail(error); return recipientFromRow(data) }
  async archive(id: string) { const { error } = await requireSupabase().from('recipients').update({ archived_at: new Date().toISOString() }).eq('id', id); fail(error) }
}
export class SupabasePaymentRepository implements PaymentSlipRepository {
  async list(filters: PaymentSlipFilters = {}) { let query = requireSupabase().from('payment_slips').select('*,payment_items(*),payment_adjustments(*)').is('archived_at', null); if (filters.status) query = query.eq('status', filters.status); if (filters.companyId) query = query.eq('company_id', filters.companyId); if (filters.recipientId) query = query.eq('recipient_id', filters.recipientId); if (filters.currency) query = query.eq('currency', filters.currency); if (filters.dateFrom) query = query.gte('payment_date', filters.dateFrom); if (filters.dateTo) query = query.lte('payment_date', filters.dateTo); if (filters.query) query = query.or(`reference.ilike.%${filters.query.replaceAll(',', '')}%,title.ilike.%${filters.query.replaceAll(',', '')}%`); query = query.order(filters.sort === 'oldest' ? 'updated_at' : filters.sort === 'amount' ? 'final_total' : 'updated_at', { ascending: filters.sort === 'oldest' }); const { data, error } = await query.limit(250); fail(error); return (data || []).map(paymentFromRow) }
  async get(id: string) { const { data, error } = await requireSupabase().from('payment_slips').select('*,payment_items(*),payment_adjustments(*)').eq('id', id).maybeSingle(); fail(error); return data ? paymentFromRow(data) : null }
  async create(slip: PaymentSlip, companyId: string, recipientId?: string) { const user = await currentUser(); const { data, error } = await requireSupabase().rpc('save_payment_slip', { p_slip_id: null, p_payment: slipToRow(slip, user.id, companyId, recipientId), p_items: slip.items, p_adjustments: slip.adjustments }); fail(error); return (await this.get(data))! }
  async update(id: string, slip: PaymentSlip, companyId: string, recipientId?: string) { const user = await currentUser(); const { data, error } = await requireSupabase().rpc('save_payment_slip', { p_slip_id: id, p_payment: slipToRow(slip, user.id, companyId, recipientId), p_items: slip.items, p_adjustments: slip.adjustments }); fail(error); return (await this.get(data))! }
  async remove(id: string) { const { error } = await requireSupabase().from('payment_slips').update({ archived_at: new Date().toISOString() }).eq('id', id); fail(error) }
  async nextReference(companyId: string) { const { data, error } = await requireSupabase().rpc('reserve_payment_reference', { p_company_id: companyId }); fail(error); return data as string }
}

const paymentFromRow = (row: Record<string, any>): CloudPaymentRecord => ({ id: row.id, createdAt: Date.parse(row.created_at), updatedAt: Date.parse(row.updated_at), companyId: row.company_id, recipientId: row.recipient_id, archivedAt: row.archived_at, slip: { company: row.company_snapshot, recipient: row.recipient_snapshot, payment: { documentType: row.document_type || 'payment-slip', customDocumentType: row.custom_document_type || '', date: row.payment_date, reference: row.reference, title: row.title, method: row.payment_method, customPaymentMethod: row.custom_payment_method || '', status: row.status, paidDate: row.paid_at?.slice(0, 10) || '', paidReference: row.paid_reference || '', bankName: row.bank_name || '', transactionReference: row.transaction_reference || '', notes: row.notes || '', adjustment: Number(row.manual_adjustment), currency: row.currency, sealText: row.seal_text || '', paperSize: row.paper_size, orientation: row.orientation }, items: (row.payment_items || []).sort((a: any, b: any) => a.display_order - b.display_order).map((item: any) => ({ id: item.id, description: item.description, quantity: Number(item.quantity), rate: Number(item.rate) })), adjustments: (row.payment_adjustments || []).sort((a: any, b: any) => a.display_order - b.display_order).map((item: any) => ({ id: item.id, label: item.label, kind: item.kind, mode: item.mode, value: Number(item.value) })) } })
