import { useEffect, useMemo, useRef, useState } from 'react'
import { ChevronLeft, ChevronRight, Cloud, Download, Eye, FilePlus2, FolderOpen, HardDrive, LoaderCircle, LockKeyhole, Moon, PlugZap, Printer, RotateCcw, Save, ShieldCheck, Sun, Unplug } from 'lucide-react'
import { SlipForm } from './components/forms/SlipForm'
import { ReviewPanel } from './components/forms/ReviewPanel'
import { PaymentSlipPreview } from './components/preview/PaymentSlipPreview'
import { WorkflowStepper, workflowSteps } from './components/common/WorkflowStepper'
import type { GoogleDriveState, PaymentSlip, WorkflowStep } from './types'
import { finalTotal, formatCurrency, subtotal } from './utils/currency'
import { generateReference } from './utils/reference'
import { errorsForStep, validateSlip } from './utils/validation'
import { generatePdf } from './utils/pdf'
import { chooseFolder, connectDrive, createGoogleDoc, disconnectDrive, driveConfigured } from './services/googleDrive'

const today = () => new Date().toLocaleDateString('en-CA')
const blank = (): PaymentSlip => ({ company: { name: '', address: '', telephone: '', email: '', registrationNumber: '', logo: '', authorizedName: '', authorizedDesignation: '', themeColor: '#0b1f3a' }, recipient: { name: '', identification: '', role: '', address: '', email: '', telephone: '' }, payment: { date: today(), reference: '', title: '', method: 'Cash', bankName: '', transactionReference: '', notes: '', adjustment: 0, currency: 'LKR', sealText: '', paperSize: 'a4', orientation: 'portrait' }, items: [{ id: crypto.randomUUID(), description: '', quantity: 1, rate: 0 }], adjustments: [] })
type Notice = { kind: 'success' | 'error'; text: string } | null
const STORAGE = { company: 'payment-slip-company', draft: 'payment-slip-draft' }
const THEME_STORAGE = 'payment-slip-theme'

export default function App() {
  const [slip, setSlip] = useState<PaymentSlip>(() => { const x = blank(); const saved = localStorage.getItem(STORAGE.company); return saved ? { ...x, company: { ...x.company, ...JSON.parse(saved) } } : x })
  const [darkMode, setDarkMode] = useState(() => { const saved = localStorage.getItem(THEME_STORAGE); return saved ? saved === 'dark' : window.matchMedia('(prefers-color-scheme: dark)').matches })
  const [activeStep, setActiveStep] = useState<WorkflowStep>('company'); const [highestStep, setHighestStep] = useState(0); const [attemptedStep, setAttemptedStep] = useState<WorkflowStep | null>(null)
  const [attempted, setAttempted] = useState(false); const [notice, setNotice] = useState<Notice>(null); const [busy, setBusy] = useState('')
  const [drive, setDrive] = useState<GoogleDriveState>({ connected: false, folderId: '', folderName: '', documentUrl: '' })
  const preview = useRef<HTMLDivElement>(null); const allErrors = useMemo(() => validateSlip(slip), [slip]); const visibleErrors = attempted || attemptedStep === activeStep ? errorsForStep(allErrors, activeStep) : {}
  const valid = Object.keys(allErrors).length === 0; const total = finalTotal(slip.items, slip.payment.adjustment, slip.adjustments)
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(null), 4500); return () => clearTimeout(timer) }, [notice])
  useEffect(() => { document.documentElement.dataset.theme = darkMode ? 'dark' : 'light'; localStorage.setItem(THEME_STORAGE, darkMode ? 'dark' : 'light') }, [darkMode])
  const tell = (kind: 'success' | 'error', text: string) => setNotice({ kind, text })
  const requireValid = (action: () => void) => { setAttempted(true); if (!valid) { tell('error', 'Please fix the highlighted fields before generating the slip.'); return } action() }
  const saveDraft = () => { localStorage.setItem(STORAGE.draft, JSON.stringify(slip)); tell('success', 'Draft saved on this device.') }
  const resetWorkflow = () => { setActiveStep('company'); setHighestStep(0); setAttemptedStep(null); setAttempted(false) }
  const loadDraft = () => { const saved = localStorage.getItem(STORAGE.draft); if (!saved) return tell('error', 'No saved draft was found on this device.'); const draft = JSON.parse(saved) as PaymentSlip; const defaults = blank(); setSlip({ ...defaults, ...draft, company: { ...defaults.company, ...draft.company }, payment: { ...defaults.payment, ...draft.payment }, adjustments: draft.adjustments || [] }); resetWorkflow(); tell('success', 'Draft loaded.') }
  const clear = () => { if ((slip.recipient.name || slip.payment.title || slip.items.some(x => x.description)) && !confirm('Clear this payment slip? Unsaved information will be lost.')) return; const next = blank(); next.company = slip.company; setSlip(next); resetWorkflow(); tell('success', 'Form cleared. Company details were kept.') }
  const another = () => { const next = blank(); next.company = slip.company; next.payment.reference = generateReference(); setSlip(next); resetWorkflow(); scrollTo({ top: 0, behavior: 'smooth' }); tell('success', 'A new payment slip is ready.') }
  const selectStep = (step: WorkflowStep) => { const index = workflowSteps.findIndex(item => item.id === step); if (index <= highestStep) { setActiveStep(step); setAttemptedStep(null); scrollTo({ top: 0, behavior: 'smooth' }) } }
  const nextStep = () => { const currentErrors = errorsForStep(allErrors, activeStep); if (Object.keys(currentErrors).length) { setAttemptedStep(activeStep); tell('error', `Please complete the ${activeStep} information before continuing.`); return } const nextIndex = Math.min(workflowSteps.findIndex(item => item.id === activeStep) + 1, workflowSteps.length - 1); setHighestStep(value => Math.max(value, nextIndex)); setActiveStep(workflowSteps[nextIndex].id); setAttemptedStep(null); scrollTo({ top: 0, behavior: 'smooth' }) }
  const previousStep = () => { const previousIndex = Math.max(workflowSteps.findIndex(item => item.id === activeStep) - 1, 0); setActiveStep(workflowSteps[previousIndex].id); setAttemptedStep(null); scrollTo({ top: 0, behavior: 'smooth' }) }
  const printSlip = () => { const dimensions = { a4: [210, 297], a5: [148, 210], b5: [176, 250], letter: [216, 279] } as const; const selected = dimensions[slip.payment.paperSize] || dimensions.a4; const [width, height] = slip.payment.orientation === 'landscape' ? [selected[1], selected[0]] : selected; const style = document.createElement('style'); style.id = 'dynamic-print-size'; style.textContent = `@media print{@page{size:${width}mm ${height}mm;margin:0}.slip{width:${width}mm!important;height:${height}mm!important;aspect-ratio:${width}/${height}!important}}`; document.head.appendChild(style); const cleanup = () => { style.remove(); window.removeEventListener('afterprint', cleanup) }; window.addEventListener('afterprint', cleanup); window.print() }
  const run = async (label: string, task: () => Promise<void>) => { try { setBusy(label); await task() } catch (e) { tell('error', e instanceof Error ? e.message : 'Something went wrong.') } finally { setBusy('') } }
  return <div className="app-shell">
    <header className="app-header"><div className="app-brand"><div className="brand-mark"><FilePlus2 /></div><div><strong>Sliply</strong><span>Payment Slip Generator</span></div></div><div className="header-status"><button className="theme-toggle" onClick={() => setDarkMode(value => !value)} aria-label={`Switch to ${darkMode ? 'light' : 'dark'} mode`} title={`Switch to ${darkMode ? 'light' : 'dark'} mode`}>{darkMode ? <Sun /> : <Moon />}<span>{darkMode ? 'Light mode' : 'Dark mode'}</span></button><div className="privacy-pill"><ShieldCheck /> Local & private</div></div></header>
    <main><section className="workspace-intro"><div><span className="eyebrow">DOCUMENT WORKSPACE</span><h1>Create a payment slip</h1><p>Complete four clear steps. Your information stays in place as you move between them.</p></div><div className="header-actions"><button className="button secondary" onClick={loadDraft}><FolderOpen /> Load draft</button><button className="button secondary" onClick={saveDraft}><Save /> Save draft</button><button className="button danger-subtle" onClick={clear}><RotateCcw /> Clear</button></div></section>
      <WorkflowStepper active={activeStep} highestIndex={highestStep} onSelect={selectStep} />
      <div className="workspace"><div className="form-pane">{activeStep === 'review' ? <ReviewPanel slip={slip} errors={allErrors} /> : <SlipForm slip={slip} errors={visibleErrors} step={activeStep} onChange={setSlip} onReference={() => setSlip({ ...slip, payment: { ...slip.payment, reference: generateReference() } })} onSaveCompany={() => { localStorage.setItem(STORAGE.company, JSON.stringify(slip.company)); tell('success', 'Company details saved on this device.') }} onLogoError={x => tell('error', x)} />}
        <div className="workflow-navigation"><button className="button secondary" type="button" onClick={previousStep} disabled={activeStep === 'company'}><ChevronLeft /> Back</button><span>Step {workflowSteps.findIndex(item => item.id === activeStep) + 1} of {workflowSteps.length}</span>{activeStep !== 'review' ? <button className="button primary" type="button" onClick={nextStep}>Continue <ChevronRight /></button> : <button className="button secondary" type="button" onClick={() => selectStep('payment')}><ChevronLeft /> Edit payment</button>}</div>
        <section className="drive-card" hidden aria-hidden="true"><div className="drive-heading"><div className="drive-icon"><Cloud /></div><div><h2>Google Drive <span>Optional</span></h2><p>{!driveConfigured ? 'Setup required — add a Google OAuth Client ID to enable this feature.' : drive.connected ? 'Connected for this browser session.' : 'Create a Google Doc copy in a folder you choose.'}</p></div><span className={`status ${drive.connected ? 'connected' : ''}`}>{drive.connected ? 'Connected' : 'Not connected'}</span></div>
          {drive.folderName && <div className="folder-display"><HardDrive /> Saving to <strong>{drive.folderName}</strong></div>}
          <div className="inline-actions"><button className="button secondary" disabled={!driveConfigured || !!busy || drive.connected} onClick={() => run('connect', async () => { await connectDrive(); setDrive({ ...drive, connected: true }); tell('success', 'Google Drive connected for this session.') })}>{busy === 'connect' ? <LoaderCircle className="spin" /> : <PlugZap />} Connect Drive</button><button className="button secondary" disabled={!drive.connected || !!busy} onClick={() => run('folder', async () => { const f = await chooseFolder(); setDrive({ ...drive, folderId: f.id, folderName: f.name }) })}><FolderOpen /> Choose folder</button><button className="button secondary" disabled={!drive.connected || !drive.folderId || !valid || !!busy} onClick={() => run('doc', async () => { const doc = await createGoogleDoc(slip, drive.folderId); setDrive({ ...drive, documentUrl: doc.url }); tell('success', 'Google Doc created successfully.') })}>{busy === 'doc' ? <LoaderCircle className="spin" /> : <FilePlus2 />} Create Google Doc</button>{drive.connected && <button className="text-button" onClick={() => { disconnectDrive(); setDrive({ connected: false, folderId: '', folderName: '', documentUrl: '' }) }}><Unplug /> Disconnect</button>}</div>{drive.documentUrl && <a className="doc-link" href={drive.documentUrl} target="_blank" rel="noreferrer">Open created Google Doc ↗</a>}
        </section><p className="privacy-note"><LockKeyhole /> Your payment information remains on this device.</p><div className="developer-mark">Developed by <a href="https://hsclogic.com/" target="_blank" rel="noreferrer">HSC Logic</a></div></div>
        <aside className="preview-pane" ref={preview}><div className="preview-toolbar"><div><Eye /><span>Live preview</span><i>{slip.payment.paperSize.toUpperCase()} · {slip.payment.orientation === 'portrait' ? 'Portrait' : 'Landscape'}</i></div><div className="total-chip"><span>Total</span><strong>{formatCurrency(total, slip.payment.currency)}</strong></div></div><div className="paper-wrap"><PaymentSlipPreview slip={slip} /></div></aside></div>
    </main>
    {activeStep === 'review' && <div className="action-dock"><div><span>Subtotal</span><strong>{formatCurrency(subtotal(slip.items), slip.payment.currency)}</strong></div><button className="button secondary" onClick={() => preview.current?.scrollIntoView({ behavior: 'smooth' })}><Eye /> Preview</button><button className="button secondary" disabled={!valid} onClick={() => requireValid(printSlip)}><Printer /> Print</button><button className="button primary" disabled={!valid || !!busy} onClick={() => requireValid(() => { setBusy('pdf'); setTimeout(() => { try { generatePdf(slip); tell('success', 'Your PDF has been downloaded.') } finally { setBusy('') } }, 30) })}>{busy === 'pdf' ? <LoaderCircle className="spin" /> : <Download />} Generate PDF</button><button className="button secondary" onClick={another}><FilePlus2 /> Another slip</button></div>}
    {notice && <div className={`toast ${notice.kind}`} role="status">{notice.kind === 'success' ? <ShieldCheck /> : <span>!</span>}{notice.text}</div>}
  </div>
}
