import { useState, type FormEvent } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { requireSupabase, supabaseConfigured } from '../../services/supabase/client'

export function AuthForm({ mode }: { mode: 'login' | 'register' | 'forgot' }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  const navigate = useNavigate(); const location = useLocation(); const destination = (location.state as { from?: string } | null)?.from || '/dashboard'
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setMessage(''); try { const client = requireSupabase(); if (mode === 'forgot') { const { error } = await client.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}${import.meta.env.BASE_URL}#/login` }); if (error) throw error; setMessage('Check your email for the password-reset link.'); return } const result = mode === 'register' ? await client.auth.signUp({ email, password }) : await client.auth.signInWithPassword({ email, password }); if (result.error) throw result.error; if (mode === 'register' && !result.data.session) setMessage('Check your email to confirm your account.'); else navigate(destination, { replace: true }) } catch (error) { setMessage(error instanceof Error ? error.message : 'Authentication failed. Please try again.') } finally { setBusy(false) } }
  return <main className="auth-page"><form className="auth-card" onSubmit={submit}><h1>{mode === 'login' ? 'Sign in' : mode === 'register' ? 'Create account' : 'Reset password'}</h1><p>Guest payment creation remains available without an account.</p>{!supabaseConfigured && <p className="auth-warning" role="status">Cloud features are not configured. Continue in guest mode.</p>}<label>Email<input type="email" required autoComplete="email" value={email} onChange={event => setEmail(event.target.value)} /></label>{mode !== 'forgot' && <label>Password<input type="password" required minLength={8} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} value={password} onChange={event => setPassword(event.target.value)} /></label>}<button className="button primary" disabled={busy || !supabaseConfigured}>{busy ? 'Please wait…' : mode === 'login' ? 'Sign in' : mode === 'register' ? 'Register' : 'Send reset link'}</button>{message && <p role="status">{message}</p>}<nav>{mode !== 'login' && <Link to="/login">Sign in</Link>}{mode === 'login' && <><Link to="/register">Register</Link><Link to="/forgot-password">Forgot password?</Link></>}<Link to="/plans">Compare plans</Link><Link to="/">Continue as guest</Link></nav></form></main>
}
