import { Building2, Contact, CreditCard, FileText, LayoutTemplate, Palette, Plus, RefreshCw, Save, Trash2, Upload } from 'lucide-react'
import type { ChangeEvent } from 'react'
import type { Errors, PaymentSlip, PaymentStatus, SavedRecipient, WorkflowStep } from '../../types'
import { calculatePaymentTotals, currencies, formatCurrency } from '../../utils/currency'
import { changePaymentStatus, paymentStatusLabels, paymentStatuses } from '../../utils/paymentStatus'
import { Field, Input, Select, TextArea } from '../common/Field'

interface Props { slip: PaymentSlip; errors: Errors; step: Exclude<WorkflowStep, 'review'>; quickMode: boolean; hasCompanyProfile: boolean; savedRecipients: SavedRecipient[]; selectedRecipientId: string; onChange: (next: PaymentSlip) => void; onReference: () => void; onSaveCompany: () => void; onClearCompany: () => void; onSelectRecipient: (id: string) => void; onSaveRecipient: () => void; onDeleteRecipient: () => void; onLogoError: (message: string) => void; onSubmit: () => void }
const Section = ({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) => <section className="form-section"><h2>{icon}{title}</h2>{children}</section>
const Advanced = ({ quick, children }: { quick: boolean; children: React.ReactNode }) => quick ? <details className="quick-advanced"><summary>Advanced options</summary><div>{children}</div></details> : <>{children}</>

export function SlipForm({ slip, errors, step, quickMode, hasCompanyProfile, savedRecipients, selectedRecipientId, onChange, onReference, onSaveCompany, onClearCompany, onSelectRecipient, onSaveRecipient, onDeleteRecipient, onLogoError, onSubmit }: Props) {
  const calculation = calculatePaymentTotals(slip.items, slip.payment.adjustment, slip.adjustments)
  const set = (group: 'company' | 'recipient' | 'payment', key: string, value: string | number) => onChange({ ...slip, [group]: { ...slip[group], [key]: value } })
  const numericValue = (value: string) => value === '' ? '' : Number(value)
  const logo = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; if (!file) return
    if (!file.type.startsWith('image/')) return onLogoError('Please select an image file.')
    if (file.size > 2 * 1024 * 1024) return onLogoError('Logo must be smaller than 2 MB.')
    const reader = new FileReader(); reader.onload = () => set('company', 'logo', String(reader.result)); reader.readAsDataURL(file)
  }
  const setItem = (i: number, key: string, value: string | number) => onChange({ ...slip, items: slip.items.map((item, index) => index === i ? { ...item, [key]: value } : item) })
  const setAdjustment = (i: number, key: string, value: string | number) => onChange({ ...slip, adjustments: slip.adjustments.map((entry, index) => index === i ? { ...entry, [key]: value } : entry) })
  const setAdjustmentKind = (i: number, kind: string) => { const labels: Record<string, string> = { discount: 'Discount', tax: 'Tax / VAT', service: 'Service charge', delivery: 'Delivery charge', charge: 'Other charge' }; onChange({ ...slip, adjustments: slip.adjustments.map((entry, index) => index === i ? { ...entry, kind: kind as typeof entry.kind, label: labels[kind] } : entry) }) }
  return <form id="payment-step-form" className="editor" onSubmit={e => { e.preventDefault(); onSubmit() }} onKeyDown={e => { if (e.key === 'Enter' && e.target instanceof HTMLInputElement && e.target.type !== 'file') { e.preventDefault(); onSubmit() } }} noValidate aria-label={`${step} step`}>
    {step === 'company' && <>
    <Section icon={<Building2 />} title="Company information">
      <div className="field-grid"><Field label="Company name" required errorKey={errors['company.name'] ? 'company.name' : undefined} error={errors['company.name']}><Input required autoComplete="organization" value={slip.company.name} onChange={e => set('company', 'name', e.target.value)} /></Field><Field label="Registration number"><Input value={slip.company.registrationNumber} onChange={e => set('company', 'registrationNumber', e.target.value)} /></Field></div>
      <Field label="Company address" required errorKey={errors['company.address'] ? 'company.address' : undefined} error={errors['company.address']}><TextArea required autoComplete="street-address" value={slip.company.address} onChange={e => set('company', 'address', e.target.value)} /></Field>
      <Advanced quick={quickMode}>
      <div className="field-grid"><Field label="Telephone"><Input type="tel" autoComplete="tel" value={slip.company.telephone} onChange={e => set('company', 'telephone', e.target.value)} /></Field><Field label="Email" errorKey={errors['company.email'] ? 'company.email' : undefined} error={errors['company.email']}><Input type="email" autoComplete="email" value={slip.company.email} onChange={e => set('company', 'email', e.target.value)} /></Field></div>
      <div className="field-grid"><Field label="Authorized person"><Input value={slip.company.authorizedName} onChange={e => set('company', 'authorizedName', e.target.value)} /></Field><Field label="Designation"><Input value={slip.company.authorizedDesignation} onChange={e => set('company', 'authorizedDesignation', e.target.value)} /></Field></div>
      <Field label="Company theme color" errorKey={errors['company.themeColor'] ? 'company.themeColor' : undefined} error={errors['company.themeColor']} hint="Used for headings, totals, borders, and the optional seal."><div className="color-control"><Input id="company-theme-picker" type="color" value={/^#[0-9a-f]{6}$/i.test(slip.company.themeColor) ? slip.company.themeColor : '#0b1f3a'} onChange={e => set('company', 'themeColor', e.target.value)} aria-label="Choose company theme color" /><Input id="company-theme-hex" value={slip.company.themeColor} pattern="#[0-9A-Fa-f]{6}" maxLength={7} onChange={e => set('company', 'themeColor', e.target.value)} aria-label="Company theme color hex value" /><Palette /></div></Field>
      <div className="inline-actions"><label className="button secondary file-button"><Upload /> Upload logo<input type="file" accept="image/*" onChange={logo} /></label>{slip.company.logo && <button type="button" className="text-button" onClick={() => set('company', 'logo', '')}>Remove logo</button>}{hasCompanyProfile && <button type="button" className="text-button" onClick={onClearCompany}>Clear saved profile</button>}<button type="button" className="button secondary push" onClick={onSaveCompany}><Save /> {hasCompanyProfile ? 'Update profile' : 'Save profile'}</button></div>
      </Advanced>
    </Section>
    </>}
    {step === 'recipient' && <>
    <Section icon={<Contact />} title="Recipient information">
      <Field label="Saved recipient" hint={savedRecipients.length ? 'Selecting a saved recipient copies their details into this slip. NIC / ID is never saved.' : 'No saved recipients yet. Enter details below and choose Save recipient.'}><Select value={selectedRecipientId} onChange={e => onSelectRecipient(e.target.value)}><option value="">Enter a new recipient</option>{savedRecipients.map(recipient => <option key={recipient.id} value={recipient.id}>{recipient.name} — {recipient.role || recipient.email || recipient.telephone || recipient.id.slice(0, 8)}</option>)}</Select></Field>
      <div className="field-grid"><Field label="Full name" required errorKey={errors['recipient.name'] ? 'recipient.name' : undefined} error={errors['recipient.name']}><Input required autoComplete="name" value={slip.recipient.name} onChange={e => set('recipient', 'name', e.target.value)} /></Field><Field label="NIC / identification"><Input value={slip.recipient.identification} onChange={e => set('recipient', 'identification', e.target.value)} /></Field></div>
      <div className="field-grid"><Field label="Role / designation" required errorKey={errors['recipient.role'] ? 'recipient.role' : undefined} error={errors['recipient.role']}><Input required value={slip.recipient.role} onChange={e => set('recipient', 'role', e.target.value)} /></Field><Field label="Telephone"><Input type="tel" autoComplete="tel" value={slip.recipient.telephone} onChange={e => set('recipient', 'telephone', e.target.value)} /></Field></div>
      <Advanced quick={quickMode}>
      <Field label="Address"><TextArea value={slip.recipient.address} onChange={e => set('recipient', 'address', e.target.value)} /></Field>
      <Field label="Email address" errorKey={errors['recipient.email'] ? 'recipient.email' : undefined} error={errors['recipient.email']}><Input type="email" autoComplete="email" value={slip.recipient.email} onChange={e => set('recipient', 'email', e.target.value)} /></Field>
      <div className="inline-actions">{selectedRecipientId && <button type="button" className="text-button" onClick={onDeleteRecipient}>Delete saved recipient</button>}<button type="button" className="button secondary push" onClick={onSaveRecipient}><Save /> {selectedRecipientId ? 'Update recipient' : 'Save recipient'}</button></div>
      </Advanced>
    </Section>
    </>}
    {step === 'payment' && <>
    <Advanced quick={quickMode}>
    <Section icon={<LayoutTemplate />} title="Document settings">
      <p className="section-description">Choose the physical page format used by the live preview, PDF download, and printing.</p>
      <div className="field-grid"><Field label="Paper size"><Select value={slip.payment.paperSize} onChange={e => set('payment', 'paperSize', e.target.value)}><option value="a4">A4 — 210 × 297 mm</option><option value="a5">A5 — 148 × 210 mm</option><option value="b5">B5 — 176 × 250 mm</option><option value="letter">Letter — 8.5 × 11 in</option></Select></Field><Field label="Orientation"><Select value={slip.payment.orientation} onChange={e => set('payment', 'orientation', e.target.value)}><option value="portrait">Portrait</option><option value="landscape">Landscape</option></Select></Field></div>
    </Section>
    </Advanced>
    <Section icon={<CreditCard />} title="Payment details">
      <div className="field-grid"><Field label="Payment date" required errorKey={errors['payment.date'] ? 'payment.date' : undefined} error={errors['payment.date']}><Input required type="date" value={slip.payment.date} onChange={e => set('payment', 'date', e.target.value)} /></Field><Field label="Payment reference" required errorKey={errors['payment.reference'] ? 'payment.reference' : undefined} error={errors['payment.reference']}><div className="input-action"><Input required value={slip.payment.reference} onChange={e => set('payment', 'reference', e.target.value)} /><button type="button" title="Generate reference" aria-label="Generate payment reference" onClick={onReference}><RefreshCw /></button></div></Field></div>
      <Field label="Payment title / purpose" required errorKey={errors['payment.title'] ? 'payment.title' : undefined} error={errors['payment.title']}><Input required value={slip.payment.title} onChange={e => set('payment', 'title', e.target.value)} /></Field>
      <Field label="Currency"><Select value={slip.payment.currency} onChange={e => set('payment', 'currency', e.target.value)}>{Object.entries(currencies).map(([code, config]) => <option key={code} value={code}>{code} — {config.symbol}</option>)}</Select></Field>
      <Advanced quick={quickMode}>
      <Field label="Payment status"><Select value={slip.payment.status} onChange={e => onChange({ ...slip, payment: changePaymentStatus(slip.payment, e.target.value as PaymentStatus) })}>{paymentStatuses.map(status => <option key={status} value={status}>{paymentStatusLabels[status]}</option>)}</Select></Field>
      {slip.payment.status === 'paid' && <div className="field-grid"><Field label="Paid date" hint="Optional" errorKey={errors['payment.paidDate'] ? 'payment.paidDate' : undefined} error={errors['payment.paidDate']}><Input type="date" value={slip.payment.paidDate} onChange={e => set('payment', 'paidDate', e.target.value)} /></Field><Field label="Paid reference" hint="Optional receipt, transfer, or settlement reference"><Input value={slip.payment.paidReference} onChange={e => set('payment', 'paidReference', e.target.value)} /></Field></div>}
      <Field label="Payment method"><Select value={slip.payment.method} onChange={e => set('payment', 'method', e.target.value)}><option>Cash</option><option>Bank Transfer</option><option>Cheque</option><option>Other</option></Select></Field>
      <Field label="Bank name"><Input value={slip.payment.bankName} onChange={e => set('payment', 'bankName', e.target.value)} /></Field>
      <Field label="Bank / transaction reference"><Input value={slip.payment.transactionReference} onChange={e => set('payment', 'transactionReference', e.target.value)} /></Field>
      </Advanced>
    </Section>
    <Section icon={<FileText />} title="Description and amount">
      {errors.items && <p className="error panel-error" role="alert">{errors.items}</p>}
      <div className="item-list">{slip.items.map((item, i) => <div className="item-card" key={item.id}><div className="item-number">{String(i + 1).padStart(2, '0')}</div><Field label="Description" required errorKey={errors[`items.${i}.description`] ? `items.${i}.description` : undefined} error={errors[`items.${i}.description`]}><Input required value={item.description} onChange={e => setItem(i, 'description', e.target.value)} /></Field><Field label="Qty" required errorKey={errors[`items.${i}.quantity`] ? `items.${i}.quantity` : undefined} error={errors[`items.${i}.quantity`]}><Input required inputMode="decimal" type="number" min="0.01" step="0.01" value={item.quantity} onChange={e => setItem(i, 'quantity', numericValue(e.target.value))} /></Field><Field label="Rate" required errorKey={errors[`items.${i}.rate`] ? `items.${i}.rate` : undefined} error={errors[`items.${i}.rate`]}><Input required inputMode="decimal" type="number" min="0" step="0.01" value={item.rate} onChange={e => setItem(i, 'rate', numericValue(e.target.value))} /></Field><div className="item-total"><span>Amount</span><strong>{formatCurrency(calculation.itemAmounts[i], slip.payment.currency)}</strong></div><button type="button" className="icon-danger" aria-label={`Remove item ${i + 1}`} title={`Remove item ${i + 1}`} disabled={slip.items.length === 1} onClick={() => onChange({ ...slip, items: slip.items.filter((_, x) => x !== i) })}><Trash2 /></button></div>)}</div>
      <button type="button" className="button secondary" data-error-key={errors.items ? 'items' : undefined} onClick={() => onChange({ ...slip, items: [...slip.items, { id: crypto.randomUUID(), description: '', quantity: 1, rate: 0 }] })}><Plus /> Add item</button>
      <Advanced quick={quickMode}>
      <div className="field-grid spaced"><Field label="Adjustment / deduction" errorKey={errors.adjustment ? 'adjustment' : undefined} error={errors.adjustment} hint="Use a negative value for a deduction."><Input inputMode="decimal" type="number" step="0.01" value={slip.payment.adjustment} onChange={e => set('payment', 'adjustment', numericValue(e.target.value))} /></Field><Field label="Notes"><TextArea value={slip.payment.notes} onChange={e => set('payment', 'notes', e.target.value)} /></Field></div>
      <div className="adjustments-heading"><div><strong>Discounts, taxes & charges</strong><span>Add fixed or percentage-based adjustments.</span></div><button type="button" className="button secondary" onClick={() => onChange({ ...slip, adjustments: [...slip.adjustments, { id: crypto.randomUUID(), label: 'Discount', kind: 'discount', mode: 'percentage', value: 0 }] })}><Plus /> Add adjustment</button></div>
      <div className="adjustment-list">{slip.adjustments.map((entry, i) => <div className="adjustment-row" key={entry.id}><Field label="Type"><Select value={entry.kind} onChange={e => setAdjustmentKind(i, e.target.value)}><option value="discount">Discount</option><option value="tax">Tax / VAT</option><option value="service">Service charge</option><option value="delivery">Delivery charge</option><option value="charge">Other charge</option></Select></Field><Field label="Label" required errorKey={errors[`adjustments.${i}.label`] ? `adjustments.${i}.label` : undefined} error={errors[`adjustments.${i}.label`]}><Input required value={entry.label} onChange={e => setAdjustment(i, 'label', e.target.value)} /></Field><Field label="Calculation"><Select value={entry.mode} onChange={e => setAdjustment(i, 'mode', e.target.value)}><option value="percentage">Percentage (%)</option><option value="fixed">Fixed amount</option></Select></Field><Field label={entry.mode === 'percentage' ? 'Percent' : 'Amount'} required errorKey={errors[`adjustments.${i}.value`] ? `adjustments.${i}.value` : undefined} error={errors[`adjustments.${i}.value`]}><Input required inputMode="decimal" type="number" min="0" step="0.01" value={entry.value} onChange={e => setAdjustment(i, 'value', numericValue(e.target.value))} /></Field><button type="button" className="icon-danger adjustment-remove" aria-label={`Remove ${entry.label || `adjustment ${i + 1}`}`} title={`Remove ${entry.label || `adjustment ${i + 1}`}`} onClick={() => onChange({ ...slip, adjustments: slip.adjustments.filter((_, x) => x !== i) })}><Trash2 /></button></div>)}</div>
      <Field label="Bottom seal / message" hint="Optional. Leave blank to hide it."><Input list="seal-options" maxLength={28} placeholder="e.g. Thank You" value={slip.payment.sealText} onChange={e => set('payment', 'sealText', e.target.value)} /><datalist id="seal-options"><option value="Thank You" /><option value="Paid" /><option value="Received" /><option value="Payment Complete" /></datalist></Field>
      </Advanced>
    </Section>
    </>}
  </form>
}
